[window]
option_as_alt = "OnlyLeft"

[colors.primary]
foreground = "#ebdbb2"
background = "#32302f"

[env]
TERM = "xterm-256color"

[font]
size = 22

[font.normal]
family = "Menlo"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001bp"
key = "P"
mods = "Alt"
